version: "3.8"

services:
  python_bot:
    build: .  # Собираем образ из Dockerfile
    ports:
      - "5000:25011"  # Пробрасываем порт 25011 на хост
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер (для разработки)
    environment: # Устанавливаем переменные окружения
      - BOT_TOKEN=6866457554:AAEkUa0m0LWs-LLRWVQ-DOv0rzR5qB1PB08
      - GOOGLE_CREDS_JSON_PATH=avid-racer-444813-g9-0ac1a0ab6ba8.json
      - GOOGLE_SHEET_NAME=gpt-bot-for-spreadsheets
      - HF_TOKEN=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